ungoldman/gh-release

bin/cli.js

The `note` field is actually the display name in settings, so a shorter identifier is better.

Simplify token message

---

CHANGELOG.md
bin/cli.js
index.js
lib/get-defaults.js

This solves two things:
(1) Allows doing a dry run that spits out what would get sent to releases API and exits, e.g.
```
$ gh-release --dry-run
{ tag_name: 'v1.0.0',
target_commitish: 'master',
name: 'v1.0.0',
body: '* init',
owner: 'bilbo',
repo: 'baggins',
draft: false,
prerelease: false }
```
(2) Allows refactoring `index.js` so prompts are handled exclusively by `bin/cli.js`.

expose `--dry-run` option

---

index.js

Ran into this today, so I thought I'd explicitly catch this error and make it easy to understand.
Now, if you run gh-release and the version in your package.json was already used for a release, an error appears with helpful instructions specific to your project:
```
A release already exists for the tag v0.0.3
Try bumping the version in your package.json.
Then push to paulcpederson/inline-block-grid and try again.
```

Report error if release exists already

---

index.js
lib/get-defaults.js
package.json

1. Adds error if you have no repository field in `package.json`
2. Formats preview in columns
3. Colors preview with chalk
4. Automatically wraps the body using the max available console width

Preview Styles

---

CHANGELOG.md
index.js

We were checking for a request error, and throwing an informative error, but if your target commit is missing, GitHub actually just returns a 404. This applies the same error to 404s as well.

:bug: error if request for target commit is a 404

---

bin/lib/get-defaults.js
test/fixtures/unreleased/CHANGELOG.md
test/fixtures/unreleased/package.json
test/index.js

The prior behavior would error if you had an "unreleased" section at the top of your changelog.
I like to keep the section there, even empty, so that I don't have to remember to add it back in when I need to add an entry.
This finds the first changelog entry with a non-null version, rather than just the first changelog entry.

Use the most recently released version when comparing versions

---

README.md
index.js

about half a dozen times i've found myself in a situation where GitHub rejects the token that is passed when attempting to tag a release.  this PR just traps the problem and points the user in the right direction to clear their existing config file.
i haven't been able to determine the root cause, and i don't know if its likely to occur again now that you've moved to using [`ghauth`](https://www.npmjs.com/package/ghauth) but if i'm not the only one it would be a lot cooler for gh-release to trigger a fresh prompt to allow the user to authenticate.  i just couldn't figure out how to do it.

trap failed authentication

---

CHANGELOG.md
README.md
bin/lib/yargs.js
index.js

Adds support for alternate API endpoint (for Github Enterprise support).
Resolves #44.
This will be a minor release.

add endpoint option

---

README.md
bin/cli.js

It wasn't obvious to me that I could use commas to specify multiple asset paths. This makes the CLI usage a bit more obvious, and allows spaces after the commas.
Fixes #52

Comma delimited assets

---

bin/cli.js

i did quite a bit of head scratching when gh-release failed in a project where my package.json was stale after a repo rename because we currently swallow the response below.
```js
{ message: 'Moved Permanently',
url: 'https://api.github.com/repositories/48707919/releases',
documentation_url: 'https://developer.github.com/v3/#http-redirects' }
```
i've invited y'all as collaborators in [`leaflet.foo.bar`](https://github.com/jgravois/leaflet.foo.bar) (which was formerly named `leaflet.foo`) in case you'd like to test the fix somewhere safe and convenient yourselves.
i don't _think_ there's a place in the existing test suite to add something like this, but happy to be proven wrong.

warn when package.json url is out of date

---

bin/lib/get-defaults.js
test/fixtures/unreleased-alt/CHANGELOG.md
test/fixtures/unreleased-alt/package.json
test/index.js

@ungoldman
Notes:
- Implementation of featured requested in issue #65 
- Code style passes linter.
- Tests updated and passing.

catch 'bracketed' unreleased changelog entries (eg. '[Unreleased]')

---

index.js

Resolves #70 by simply concatenating the endpoint with the formatted path (which always starts with a `/`).  Also strips trailing slashes from the endpoint to avoid having multiple slashes.  I know there's been other work done on this, but there hasn't been any progress made in a while on that, and we're looking to use gh-release with projects which are in GitHub enterprise soon, so I figured I would take another stab at it.

Fix enterprise github API access

---

CHANGELOG.md
README.md
bin/cli.js
bin/lib/get-defaults.js
bin/lib/preview.js
bin/lib/yargs.js
index.js

This PR adds the following to the gh-release CLI:
- A `--noconfirm` flag for skipping the confirmation prompt (modeled after Arch Linux' pacman's `--noconfirm`)
- The ability to read an authentication token from the `GH_RELEASE_GITHUB_API_TOKEN` environment variable
These two features combined allow for gh-release to be used in continuous-delivery systems (like Jenkins) where user interaction is not possible.  It also allows these systems to work with multiple GitHub APIs (i.e. github.com and a self-hosted Enterprise GitHub) by simply swapping out the token environment variable.
Resolves #75

Support non-interactive continuous-delivery system use cases

---

package.json

npm is reporting security vulnerabilities for gh-release when installed due to some out of date deps.
The tests pass, and only one method is used from inquirer, so even though this update would skip like 5 major versions the interface for that method is the same and it should work fine.

update inquirer and deep-extend to fix reported vulnerabilities

---

bin/cli.js

Inquirer now uses the promise syntax.
/cc @bcomnes @rgwozdz

#78 - use promise syntax for inquirer prompt

---

bin/lib/get-defaults.js
test/fixtures/no-versions/CHANGELOG.md
test/fixtures/no-versions/package.json
test/index.js

This PR fixes an unhandled exception when the CHANGELOG.md file doesn't contain any versions and instead returns an understandable error message.

Fix unhandled exception when changelog contains no versions

---

bin/cli.js
index.js
package.json

This PR adds an asset upload progress indicator to gh-release by returning an `EventEmitter` from the `Release` function and proxying the events emitted by gh-release-assets out to the consumer.  It also adds a progress bar to the CLI via the [gauge](https://github.com/iarna/gauge) library.  I've tested this against a personal repo uploading multiple files of various sizes and it all looks good!  Let me know if anything should be changed or updated!
Resolves #49

Add an asset upload progress indicator

---

bin/cli.js

GitHub sometimes returns an array of errors instead of just one. this tweak ensures that they can be quickly parsed visually.
related: #82
```bash
> [object Object],[object Object],[object Object]
```
becomes
```bash
> [{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}]
```

when an array of errors are returned, ensure they are readable

---

index.js

This updates `gh-release` to allow passing `assets` as an object (for [asset renaming](https://github.com/hypermodules/gh-release-assets#usage))) when used in a Node script. Currently, you'll get the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
at validateString (internal/validators.js:121:11)
at Object.join (path.js:1039:7)
at /.../calcite-components/node_modules/gh-release/index.js:138:23
at Array.map (<anonymous>)
at Request._callback (/.../calcite-components/node_modules/gh-release/index.js:137:37)
at Request.self.callback (/.../calcite-components/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.EventEmitter.emit (domain.js:486:12)
at Request.<anonymous> …
```

feat: allow passing asset object as gh-release-assets supports

---

CHANGELOG.md
bin/cli.js
index.js
package.json

For some reason, simple-get would just timeout when using gh-release on some orgs.  I thought it was an issue with the device token permissions, but its not.  The GitHub API is weird, and finicky, and IME using octokit, despite its constant churn, is probably the best approach here.  It also generally improves errors that get returned, though most of our error handling I left the same.
I've tested the following scenarios:
- Normal working scenario
- Missing tag
- Bad credentials
- Asset uploads
Everything still seems to work.

Use octokit instead of simple-get

---

.github/workflows/test.yml

This way trivial actions updates just land, and nobody has to do anything

Automerge dependabot actions updates

---

CHANGELOG.md
bin/lib/get-defaults.js
test/fixtures/unreleased-empty-subsections/CHANGELOG.md
test/fixtures/unreleased-empty-subsections/package.json
test/get-defaults-test.js
test/index.js

My team likes to keep the 6 subsection headings from [keepachangelog](https://keepachangelog.com/en/1.0.0/#how) in `CHANGELOG.md` that way we don't have to remember the categories. This change only prevents the release if there are any bullets in any of the subsections.

allow unreleased CHANGELOG section if all subsections are empty

---

bin/lib/get-defaults.js

This allow to read dynamically changes package.json file.
For example, in runtime when we run script that update package.json version and create release on github.
* In case, when we use `require`, it will holds content of package.json and not change it while script not started again. So, we can't read actual version from it, because it changed in runtime
* In case, when we use `read`, we always read fresh state of package.json with latest actual changes

Replace static "require" to dynamic "read"

---

package.json

- removed tap-spec since it's unmaintained and adds a lot of security warnings
- removed live-server for same reason as above
- added serve to dev-deps to replace live-server

deps(dev): rm live-server, tap-spec, use serve

---

bin/cli.js
package.json

The `chalk` module is now ESM-only. Since `gh-release` is not, and we only use it in one place to make a CLI error message red, I think it is better to just remove it as a dep altogether. Seems silly to add a dependency for making a single CLI message red anyway.

deps: rm chalk

---

.npmrc

**tl;dr:**
Removing `.npmrc` file so lock gets generated locally for `npm audit`. `package-lock.json` is already listed in `.gitignore`, so won't show up in version control.
---
Thousands of years ago, there were no package lock files. Then came yarn, then npm followed suit. Many maintainers explicitly disabled lock files, because they made automated tests in CI environments less likely to catch new bugs introduced by dependencies, and generally added a lot of noise to version control while not being particularly useful for module maintainers.
Now lock files are ubiquitous, as well as being necessary for auditing dependencies for security vulnerabilities.
This repo (and many like it) has a `.npmrc` file that disables generation of the lock file in local development. However, this very …

remove .npmrc

---

.github/dependabot.yml

This PR explicitly sets dependabot's `versioning-strategy` to `increase`, making Dependabot always bump versions in the package.json.
This repo hasn't had any Dependabot PRs opened in over 2 years. I suspect the cause for that is that Dependabot is running in library mode (see [Dependabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#versioning-strategy--)). In library mode Dependabot will sometimes only bump versions in the lockfile (which this repo doesn't have).
The other option is that Dependabot has been disabled in the repo settings - which I can't check because I have no access.
Enabling Dependabot would be beneficial to the project because, among other things, it would automatically patch dependencies with known …

chore: dependabot explicit versioning-strategy

---

package.json

Remove `npm-run-all` because it's not being used (which is great because the library has been abandoned for over 6 years now)

chore: remove unused npm-run-all
